// Generated by CoffeeScript 1.6.3
(function() {
  var candidates;

  candidates = {};

  module.exports = {
    vote: function(req, res) {
      res.render('vote.jade', {
        title: 'Sign up at' + app.locals.config.name
      });
    }
  };

}).call(this);
